/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://bxbjnlundjar5kyk3lm55aia2y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lr4m4hyfhjebpmdhhahyj2bjne",
    "aws_cognito_identity_pool_id": "us-east-1:91562b8f-72c8-446c-a1c0-8040cce44793",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kVCrJWeeR",
    "aws_user_pools_web_client_id": "4kts81iarc91jj1mi5vhfeq9kl",
    "oauth": {}
};


export default awsmobile;
